name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python and pre-commit
      uses: ./.github/actions/setup-ci
    - name: Pre-commit
      run: |
        SKIP=unittests uv run pre-commit run --all-files --color=always
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python and pre-commit
      uses: ./.github/actions/setup-ci
    - name: Test with pytest
      run: |
        uv run python -m pytest . -n auto
